// Generated by CoffeeScript 1.9.3
(function() {
  module.exports = function(grunt) {
    var coffeeRename;
    coffeeRename = function(dest, src) {
      return dest + '/' + src.replace(/\.coffee$/, '.js');
    };
    grunt.initConfig({
      watch: {
        tasks: ["coffee"],
        files: ["configs/**/*.coffee", "lib/**/*.coffee", "models/**/*.coffee", "routes/**/*.coffee", "tests/helpers/*.coffee"],
        options: {
          spawn: false
        }
      },
      coffee: {
        compile: {
          files: [
            {
              expand: true,
              cwd: 'configs',
              src: ['**/*.coffee'],
              dest: 'configs',
              rename: coffeeRename
            }, {
              expand: true,
              cwd: 'models',
              src: ['**/*.coffee'],
              dest: 'models',
              rename: coffeeRename
            }, {
              expand: true,
              cwd: 'lib',
              src: ['**/*.coffee'],
              dest: 'lib',
              rename: coffeeRename
            }, {
              expand: true,
              cwd: 'routes',
              src: ['**/*.coffee'],
              dest: 'routes',
              rename: coffeeRename
            }, {
              expand: true,
              cwd: 'tests/helpers',
              src: ['*.coffee'],
              dest: 'tests/helpers',
              rename: coffeeRename
            }
          ]
        }
      }
    });
    grunt.loadNpmTasks("grunt-contrib-coffee");
    grunt.loadNpmTasks("grunt-contrib-watch");
    return grunt.registerTask("default", "coffee");
  };

}).call(this);
