// Generated by CoffeeScript 1.9.3
(function() {
  var CoreAPIClient, exports, request;

  request = require("request");

  CoreAPIClient = (function() {
    CoreAPIClient.prototype.host = null;

    CoreAPIClient.prototype.commands = {
      "create_account": "post",
      "create_bank_withdrawal": "post",
      "publish_order": "post",
      "cancel_order": "del",
      "create_payment": "post",
      "process_payment": "put",
      "cancel_payment": "del",
      "wallet_balance": "get",
      "wallet_info": "get",
      "cancel_withdrawal": "del",
      "process_bank_withdrawal": "put"
    };

    function CoreAPIClient(options) {
      if (options == null) {
        options = {};
      }
      console.log('The host name is ' + options.host);
      if (options.host) {
        this.host = options.host;
      }
    }

    CoreAPIClient.prototype.send = function(command, data, callback) {
      var e, i, len, param, url;
      if (callback == null) {
        callback = function() {};
      }
      url = "http://" + this.host + "/" + command;
      for (i = 0, len = data.length; i < len; i++) {
        param = data[i];
        url += "/" + param;
        console.log(url);
      }
      if (this.commands[command]) {
        console.log(this.commands[command]);
        try {
          return request[this.commands[command]](url, {
            json: true
          }, callback);
        } catch (_error) {
          e = _error;
          console.error(e);
          return callback("Bad response '" + e + "'");
        }
      } else {
        return callback("Invalid command '" + command + "'");
      }
    };

    CoreAPIClient.prototype.sendWithData = function(command, data, callback) {
      var e, options, uri;
      if (callback == null) {
        callback = function() {};
      }
      uri = "http://" + this.host + "/" + command;
      console.log(uri);
      if (this.commands[command]) {
        options = {
          uri: uri,
          method: this.commands[command],
          json: data
        };
        try {
          return request(options, callback);
        } catch (_error) {
          e = _error;
          console.error(e);
          return callback("Bad response " + e);
        }
      } else {
        return callback("Invalid command '" + command + "'");
      }
    };

    return CoreAPIClient;

  })();

  exports = module.exports = CoreAPIClient;

}).call(this);
