// Generated by CoffeeScript 1.10.0
(function() {
  var exports;

  exports = module.exports = {
    CURRENCIES: {
      BTC: 1,
      XWBC: 2,
      USD: 3,
      GBP: 4
    },
    AVAILABLE_MARKETS: {
      XWBC_BTC: 1,
      XWBC_USD: 2,
      XWBC_GBP: 3
    },
    CURRENCY_NAMES: {
      BTC: 'Bitcoin',
      XWBC: 'LXCCoin',
      USD: 'US Dollar',
      GBP: 'British Pound'
    },
    WITHDRAWAL_FEES: {
      BTC: 20000,
      XWBC: 2000000
    },
    BANK_WITHDRAWAL_FEES: {
      EU: .25,
      Inter: .20
    },
    BANK_WITHDRAWAL_MINIMUM: {
      EU: 150,
      Inter: 150
    },
    BANK_WITHDRAWAL_FEE_MINIMUM: {
      EU: 20,
      Inter: 25
    },
    DEFAULT_WITHDRAWAL_FEE: 200000
  };

}).call(this);
