// Generated by CoffeeScript 1.9.3
(function() {
  var speakeasy;

  require("./../../helpers/spec_helper");

  speakeasy = require("speakeasy");

  describe("Order", function() {
    var marketStats;
    marketStats = void 0;
    beforeEach(function(done) {
      marketStats = GLOBAL.db.MarketStats.build();
      return GLOBAL.db.sequelize.sync({
        force: true
      }).complete(function() {
        return done();
      });
    });
    return describe("calculateGrowthRatio", function() {
      describe("when the last price is 0.2 and the new price is 0.1", function() {
        return it("returns -50", function() {
          return GLOBAL.db.MarketStats.calculateGrowthRatio(0.2, 0.1).should.eql(-50);
        });
      });
      describe("when the last price is 2 and the new price is 3", function() {
        return it("returns 50", function() {
          return GLOBAL.db.MarketStats.calculateGrowthRatio(2, 3).should.eql(50);
        });
      });
      return describe("when the last price is 2 and the new price is 2.5", function() {
        return it("returns 25", function() {
          return GLOBAL.db.MarketStats.calculateGrowthRatio(2, 2.5).should.eql(25);
        });
      });
    });
  });

}).call(this);
