// Generated by CoffeeScript 1.9.3
(function() {
  var speakeasy;

  require("./../../helpers/spec_helper");

  speakeasy = require("speakeasy");

  describe("User", function() {
    return describe("hashPassword", function() {
      return it("returns the hashed password", function() {
        var password;
        password = "testPassword";
        return GLOBAL.db.User.hashPassword(password).should.eql("f7dfe3adc9848f0d258f16ecaf79a524f13e704620a653885c913b1873774f62");
      });
    });
  });

}).call(this);
