// Generated by CoffeeScript 1.10.0
(function() {
  var Bank, JsonRenderer, MarketHelper;

  JsonRenderer = void 0;

  MarketHelper = void 0;

  Bank = GLOBAL.db.Bank;

  MarketHelper = require('../lib/market_helper');

  JsonRenderer = require('../lib/json_renderer');

  module.exports = function(app) {
    app.get("/bank/:id?", function(req, res) {
      if (!req.user) {
        return JsonRenderer.error(null, res, 401, false);
      }
      return Bank.findById(req.user.id, function(err, bank) {
        if (err) {
          console.error(err);
        }
        if (bank) {
          return res.json(JsonRenderer.bank(bank));
        }
        if (!bank) {
          return JsonRenderer.error(null, res, 200, false);
        }
      });
    });
    app.post('/bank', function(req, res) {
      var newBankAddress, newBankCity, newBankPostCode, newBankname, newPreferredCurrency, newcountry, newiban, newname, newswift;
      newname = req.body.name;
      newBankname = req.body.bank_name;
      newBankAddress = req.body.bank_address;
      newBankCity = req.body.bank_city;
      newBankPostCode = req.body.bank_post_code;
      newcountry = req.body.country;
      newiban = req.body.iban;
      newswift = req.body.swift;
      newPreferredCurrency = req.body.preferred_currency;
      if (!req.user) {
        return JsonRenderer.error('Please auth.', res);
      }
      return Bank.findById(req.user.id, function(err, bank) {
        if (err) {
          if (err) {
            return JsonRenderer.error(err, res);
          }
        }
        if (!bank) {
          return Bank.createNewBank({
            id: req.user.id,
            Name: newname,
            bankCountry: newcountry,
            BankName: newBankname,
            BankAddress: newBankAddress,
            bankPostalCode: newBankPostCode,
            bankCity: newBankCity,
            preferredCurrency: newPreferredCurrency,
            IBAN: newiban,
            SWIFT: newswift
          }, function(err, bank) {
            if (err) {
              if (errconsole.log(err)) {
                return JsonRenderer.error(err, res);
              }
            }
            return res.json(JsonRenderer.bank(bank));
          });
        }
      });
    });
    app.put('/bank/:id', function(req, res) {
      if (!req.user) {
        return JsonRenderer.error('Please auth.', res);
      }
      return Bank.findById(req.user.id, function(err, bank) {
        if (err) {
          console.error(err);
        }
        if (bank) {
          return bank.updateAttributes(req.body, function(err, bank) {
            if (err) {
              console.log(err);
            }
            if (err) {
              return JsonRenderer.error(err, res);
            }
            return res.json(JsonRenderer.bank(bank));
          });
        }
      });
    });
    return app.get('/bank/:id', function(req, res) {
      if (!req.user) {
        return JsonRenderer.error('Please auth.', res);
      }
      return bank.findById(req.user.id, function(err, bank) {
        if (err) {
          console.error(err);
        }
        return res.json(JsonRenderer.bank(bank));
      });
    });
  };

}).call(this);
