// Generated by CoffeeScript 1.10.0
(function() {
  var BANNED_USERNAMES_REGEX, Emailer, MarketHelper, _, crypto, phonetic, speakeasy;

  MarketHelper = require("../lib/market_helper");

  crypto = require("crypto");

  speakeasy = require("speakeasy");

  Emailer = require("../lib/emailer");

  phonetic = require("phonetic");

  _ = require("underscore");

  BANNED_USERNAMES_REGEX = /admin|coinnext/ig;

  module.exports = function(sequelize, DataTypes) {
    var User;
    User = sequelize.define("User", {
      uuid: {
        type: DataTypes.UUID,
        defaultValue: DataTypes.UUIDV4,
        allowNull: false,
        unique: true,
        validate: {
          isUUID: 4
        }
      },
      email: {
        type: DataTypes.STRING,
        allowNull: false,
        unique: true,
        validate: {
          isEmail: true
        }
      },
      name: {
        type: DataTypes.STRING,
        allowNull: true
      },
      firstname: {
        type: DataTypes.STRING,
        allowNull: true
      },
      lastname: {
        type: DataTypes.STRING,
        allowNull: true
      },
      address1: {
        type: DataTypes.STRING,
        allowNull: true
      },
      address2: {
        type: DataTypes.STRING,
        allowNull: true
      },
      postcode: {
        type: DataTypes.STRING,
        allowNull: true
      },
      city: {
        type: DataTypes.STRING,
        allowNull: true
      },
      country: {
        type: DataTypes.STRING,
        allowNull: true
      },
      phone: {
        type: DataTypes.STRING,
        allowNull: true
      },
      alternate_email: {
        type: DataTypes.STRING,
        allowNull: true
      },
      skypeId: {
        type: DataTypes.STRING,
        allowNull: true
      },
      password: {
        type: DataTypes.STRING,
        allowNull: false,
        validate: {
          len: [5, 500]
        }
      },
      username: {
        type: DataTypes.STRING,
        allowNull: false,
        unique: true,
        validate: {
          isAlphanumericAndUnderscore: function(value) {
            var message;
            message = "The username can have letters, numbers and underscores and should be longer than 4 characters and shorter than 16.";
            if (!/^[a-zA-Z0-9_]{4,15}$/.test(value)) {
              throw new Error(message);
            }
          },
          isAllowedUsername: function(value) {
            var message;
            message = "This username is not allowed";
            if (BANNED_USERNAMES_REGEX.test(value)) {
              throw new Error(message);
            }
          }
        }
      },
      email_verified: {
        type: DataTypes.BOOLEAN,
        allowNull: false,
        defaultValue: false
      },
      chat_enabled: {
        type: DataTypes.BOOLEAN,
        allowNull: false,
        defaultValue: true
      },
      email_auth_enabled: {
        type: DataTypes.BOOLEAN,
        allowNull: false,
        defaultValue: true
      }
    }, {
      tableName: "users",
      classMethods: {
        findById: function(id, callback) {
          if (callback == null) {
            callback = function() {};
          }
          return User.find(id).complete(callback);
        },
        findByToken: function(token, callback) {
          var query;
          if (callback == null) {
            callback = function() {};
          }
          query = {
            where: {
              token: token
            },
            include: [
              {
                model: GLOBAL.db.User
              }
            ]
          };
          return GLOBAL.db.UserToken.find(query).complete(function(err, userToken) {
            if (userToken == null) {
              userToken = {};
            }
            return callback(err, userToken.user);
          });
        },
        findByEmail: function(email, callback) {
          if (callback == null) {
            callback = function() {};
          }
          return User.find({
            where: {
              email: email
            }
          }).complete(callback);
        },
        findByUsername: function(username, callback) {
          if (callback == null) {
            callback = function() {};
          }
          return User.find({
            where: {
              username: username
            }
          }).complete(callback);
        },
        hashPassword: function(password) {
          return crypto.createHash("sha256").update("" + password + (GLOBAL.appConfig().salt), "utf8").digest("hex");
        },
        passwordMeetsRequirements: function(password) {
          if (password == null) {
            password = "";
          }
          if (password.length < 8) {
            return false;
          }
          if (!/[0-9]/.test(password)) {
            return false;
          }
          return true;
        },
        createNewUser: function(data, callback) {
          var userData;
          userData = _.extend({}, data);
          if (!User.passwordMeetsRequirements(userData.password)) {
            return callback("Your password doest not meet the minimum requirements. It must be at least 8 characters and cointain at least one one number.", null);
          }
          userData.password = User.hashPassword(userData.password);
          userData.username = User.generateUsername(data.email);
          return User.create(userData).complete(callback);
        },
        generateUsername: function(seed) {
          seed = crypto.createHash("sha256").update("username_" + seed + (GLOBAL.appConfig().salt), "utf8").digest("hex");
          return phonetic.generate({
            seed: seed
          });
        }
      },
      instanceMethods: {
        isValidPassword: function(password) {
          return this.password === User.hashPassword(password);
        },
        sendChangePasswordLink: function(callback) {
          if (callback == null) {
            callback = function() {};
          }
          return GLOBAL.db.UserToken.generateChangePasswordTokenForUser(this.id, this.uuid, (function(_this) {
            return function(err, userToken) {
              var data, emailer, options, passUrl;
              passUrl = "/change-password/" + userToken.token;
              data = {
                "pass_url": passUrl
              };
              options = {
                to: {
                  email: _this.email
                },
                subject: "Change password request",
                template: "change_password"
              };
              emailer = new Emailer(options, data);
              emailer.send(function(err, result) {
                if (err) {
                  return console.error(err);
                }
              });
              return callback();
            };
          })(this));
        },
        sendEmailVerificationLink: function(type, callback) {
          if (type == null) {
            type = "activation";
          }
          if (callback == null) {
            callback = function() {};
          }
          if (this.email_verified) {
            return callback();
          }
          return GLOBAL.db.UserToken.generateEmailConfirmationTokenForUser(this.id, this.uuid, (function(_this) {
            return function(err, userToken) {
              var data, emailer, options, templateFile;
              if (type === "activation") {
                templateFile = "reactivation_email";
              }
              if (type === "reactivation") {
                templateFile = "confirm_email";
              }
              data = {
                "verification_url": "/verify/" + userToken.token
              };
              options = {
                to: {
                  email: _this.email
                },
                subject: "Email verification",
                template: templateFile
              };
              emailer = new Emailer(options, data);
              emailer.send(function(err, result) {
                if (err) {
                  return console.error(err);
                }
              });
              return callback();
            };
          })(this));
        },
        changePassword: function(password, callback) {
          var newHash, oldHash;
          if (callback == null) {
            callback = function() {};
          }
          oldHash = this.password;
          newHash = User.hashPassword(password);
          if (newHash === oldHash) {
            return callback("You new password must be different from the old one.");
          }
          if (!User.passwordMeetsRequirements(password)) {
            return callback("Your password doest not meet the minimum requirements. It must be at least 8 characters and cointain at least one one number.");
          }
          this.password = newHash;
          return this.save().complete(callback);
        },
        setEmailVerified: function(callback) {
          if (callback == null) {
            callback = function() {};
          }
          this.email_verified = true;
          return this.save().complete(callback);
        },
        emailVerified: function() {
          return this.email_verified;
        },
        canTrade: function() {
          if (!this.email_verified || this.firstname === "" || this.lastname === "" || this.address1 === "" || this.postcode === "" || this.city === "" || this.country === "" || this.phone === "") {
            return false;
          } else {
            return true;
          }
        },
        walletCreated: function() {
          return Wallet.find({
            where: {
              user_id: this.uuid,
              currency: MarketHelper.getCurrency(2)
            }
          }).complete(callback);
        },
        updateSettings: function(data, callback) {
          var email_changed;
          if (callback == null) {
            callback = function() {};
          }
          if (data.chat_enabled != null) {
            this.chat_enabled = !!data.chat_enabled;
          }
          if (data.email_auth_enabled != null) {
            this.email_auth_enabled = !!data.email_auth_enabled;
          }
          if ((data.username != null) && data.username !== this.username) {
            this.username = data.username;
          }
          if ((data.name != null) && data.name !== this.name) {
            this.name = data.name;
          }
          if ((data.firstname != null) && data.firstname !== this.firstname) {
            this.firstname = data.firstname;
          }
          if ((data.lastname != null) && data.lastname !== this.lastname) {
            this.lastname = data.lastname;
          }
          if ((data.email != null) && data.email !== this.email) {
            this.email_verified = false;
          }
          if ((data.email != null) && data.email !== this.email) {
            email_changed = true;
          }
          if ((data.email != null) && data.email !== this.email) {
            this.email = data.email;
          }
          if ((data.alternate_email != null) && data.alternate_email !== this.alternate_email) {
            this.alternate_email = data.alternate_email;
          }
          if ((data.name != null) && data.name !== this.name) {
            this.name = data.name;
          }
          if ((data.address1 != null) && data.address1 !== this.address1) {
            this.address1 = data.address1;
          }
          if ((data.address2 != null) && data.address2 !== this.address2) {
            this.address2 = data.address2;
          }
          if ((data.postcode != null) && data.postcode !== this.postcode) {
            this.postcode = data.postcode;
          }
          if ((data.city != null) && data.city !== this.city) {
            this.city = data.city;
          }
          if ((data.country != null) && data.country !== this.country) {
            this.country = data.country;
          }
          if ((data.phone != null) && data.phone !== this.phone) {
            this.phone = data.phone;
          }
          if ((data.skypeId != null) && data.skypeId !== this.skypeId) {
            this.skypeId = data.skypeId;
          }
          return this.save().complete(callback);
        },
        recenltySignedUp: function() {
          return this.created_at > (Date.now() - 60000);
        },
        emailUpdated: function(email, callback) {
          if (callback == null) {
            callback = function() {};
          }
          if (this.email_verified) {
            return callback();
          }
          return callback;
        }
      }
    });
    return User;
  };

}).call(this);
